openapi: 3.0.3
info:
  title: Water Usage History
  description: |
    This microservice provides access to recorded water usage values
  version: 1.0.0
servers:
  - url: '/api/usage-history'
    description: WISdoM

  - url: 'http://localhost:8000'
    description: Development

components:
  securitySchemes:
    WISdoM:
      description: |
        Access Tokens issued by the User Management Service
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

paths:
  /:
    get:
      responses:
        200:
          description: Hello There response
          content:
            text/plain:
              schema:
                type: string
                pattern: '^hello there$'
  
