openapi: 3.0.2
info:
  title: Water Usage History
  description: |
    This microservice provides access to recorded water usage values
  version: 1.0.0
servers:
  - url: '/api/usage-history'
    description: WISdoM

  - url: 'http://localhost:8000'
    description: Development

components:
  securitySchemes:
    WISdoM:
      description: |
        Access Tokens issued by the User Management Service
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

  schemas:
    UsageRecord:
      type: object
      properties:
        time:
          type: string
          format: date-time
        amount:
          type: number
        usageType:
          type: string
          format: uuid
          nullable: true
        consumerID:
          type: string
          format: uuid
          nullable: true
        ars:
          type: string
          nullable: true
          pattern: '[01][0-6][0-9]{10}'
        
        

paths:
  /:
    get:
      security:
        - WISdoM: ["usage-history:read"]
      
      responses:
        200:
          description: |
            Usage List

            The response contains all recorded water usages currently available
            in the database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsageRecord"            
  
