openapi: 3.0.3
info:
  title: Water Usage History Microservice
  description: |
    [![GitHub Repo](https://img.shields.io/badge/GitHub%20Repository-service--water--usage--history-333?style=for-the-badge&logo=github)](https://github.com/wisdom-oss/service-water-usage-history)
    
    This microservice allows authenticated API users to retrieve the recorded
    water usages for a known consumer.
  

  version: 3.0.0

components:
  schemas:
    Error:
      description: A error returned by the API
      type: object
      properties:
        type:
          type: string
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        error:
          type: string
      required:
        - type
        - status
        - title
        - detail
        - instance

    UsageRecord:
      description: A single usage record as shown in the database
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        amount:
          type: number
          format: float8
        usageType:
          type: string
          format: uuid
        consumer:
          type: string
          format: uuid
        municipality:
          type: string
          title: Official Regional Code
          description: |-
            This code allows the identification of the municipality in which the
            usage record has been taken. It is only applicable in Germany.
      required:
        - timestamp
        - amount
        - municipality

  responses:
    Usages:
      description: A list of usage records
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UsageRecord'

paths:
  /:
    get:
      summary: Get Usage Records
      parameters:
        - in: query
          name: page-size
          description: The size of the response that is returned (to allow pagination)
          allowEmptyValue: false
          allowReserved: false
          required: false
          schema:
            type: integer
            default: 10000
        - in: query
          name: page
          description: The page that shall be returned
          allowEmptyValue: false
          allowReserved: false
          required: false
          schema:
            type: integer
            default: 1
      responses:
        200:
          $ref: '#/components/responses/Usages'
        413:
          description: Page Size Too Large
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
  /{consumer-id}:
    get:
      summary: Get Usage Records for Consumer
      parameters:
        - in: path
          name: consumer-id
          description: The UUID assigned to the consumer
          allowEmptyValue: true
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: page-size
          description: The size of the response that is returned (to allow pagination)
          allowEmptyValue: false
          allowReserved: false
          required: false
          schema:
            type: integer
            default: 10000
        - in: query
          name: page
          description: The page that shall be returned
          allowEmptyValue: false
          allowReserved: false
          required: false
          schema:
            type: integer
            default: 1
      responses:
        200:
          $ref: '#/components/responses/Usages'
        400:
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
        413:
          description: Page Size Too Large
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'