openapi: 3.0.3
info:
  # TODO: Change Information
  title: Microservice Template
  description: Microservice Template
  version: 1.0.0
servers:
  - url: '/api/xzy' # TODO: Replace xyz with actual deployment path
    description: WISdoM

  - url: 'http://localhost:8000'
    description: Development

components:
  # TODO: Remove if service won't handle private data
  securitySchemes:
    WISdoM:
      description: |
        Access Tokens issued by the User Management Service
      type: openIdConnect
      openIdConnectUrl: /api/auth/.well-known/openid-configuration

paths:
  /:
    get:
      responses:
        200:
          description: Hello There response
          content:
            text/plain:
              schema:
                type: string
                pattern: '^hello there$'
  
