name: Run Tests
on: ["push", "pull_request"]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: wisdom-oss/actions/go-test@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}