name: "Go Tests"
on: [pull_request,push]

env:
  PG_HOST: ${{ secrets.TESTS_PG_HOST }}
  PG_USER: ${{ secrets.TESTS_PG_USER }}
  PG_PASS: ${{ secrets.TESTS_PG_PASS }}

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    permissions:
      checks: write
      pull-requests: write
      issues: read
      contents: read

    steps:
      - uses: wisdom-oss/actions/go-test@main