name: tests
on: ["push", "pull_request"]

env:
    PGUSER: ${{ secrets.TESTS_PG_USER }}
    PGPASSWORD: ${{ secrets.TESTS_PG_PASS }}
    PGHOST: ${{ secrets.TESTS_PG_HOST }}
    PGDATABASE: wisdom
    PGSSLMODE: disable
    
jobs:
    test:
        runs-on: self-hosted
        steps:
            - uses: wisdom-oss/actions/go-test@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}